openforcefield/openff-qcsubmit

- qcsubmit/factories.py
- qcsubmit/tests/test_factories.py
This now means that molecules with torsions highlighted by a component or some outside source are checked that they are connected before making the dataset, if they are not the molecule is failed.
> Check torsion connections

- qcsubmit/tests/test_workflow_components.py
- qcsubmit/workflow_components/__init__.py
- qcsubmit/workflow_components/filters.py
Molecules can now be filtered depending on if they contain certain allowed/disallowed substructures defined as tagged smarts patterns.
> Added smarts substructure filter and tests.

- devtools/conda-envs/ani_env.yaml
- devtools/conda-envs/psi4_env.yaml
- devtools/conda-envs/test_env.yaml
- qcsubmit/common_structures.py
- qcsubmit/datasets.py
- qcsubmit/exceptions.py
- qcsubmit/tests/test_datasets.py
- qcsubmit/workflow_components/filters.py
> Basis set coverage checking

- devtools/conda-envs/psi4_env.yaml
- devtools/conda-envs/test_env.yaml
- qcsubmit/datasets.py
- qcsubmit/tests/test_datasets.py
- qcsubmit/tests/test_submissions.py
This PR fixes #24 for both rdkit and openeye backends. 
Datasets now have a function `visualize` where users can also specify the backend toolkit to use, this defaults to openeye.
> Visualize via pdf

- qcsubmit/constraints.py
- qcsubmit/datasets.py
- qcsubmit/exceptions.py
- qcsubmit/tests/test_datasets.py
- qcsubmit/tests/test_results.py
- qcsubmit/utils.py
- qcsubmit/workflow_components/fragmentation.py
This PR allows datasets to be combined into larger datasets via `new_dataset = dataset1 + dataset2`. 
Dataset types must match as the datasets have different definitions of equal entries and deduplication is applied to initial molecules.
> Dataset combining

- qcsubmit/common_structures.py
- qcsubmit/data/settings.json
- qcsubmit/data/settings.yaml
- qcsubmit/data/settings_with_workflow.json
- qcsubmit/data/settings_with_workflow.yaml
- qcsubmit/datasets.py
- qcsubmit/exceptions.py
- qcsubmit/factories.py
- qcsubmit/results.py
- qcsubmit/tests/test_datasets.py
- qcsubmit/tests/test_factories.py
- qcsubmit/tests/test_serializers.py
- qcsubmit/tests/test_submissions.py
- qcsubmit/utils.py
This allows factories and datasets to handle multiple QC specs which are heavily validated to avoid run time issues and can be submitted simultaneously. We also expand the qc spec to store wavefunction protocols allowing the saving of the wavefunction.
The second major change is that all datasets now have the cmiles stored at the molecule level, this is still hidden in the extras field but should allow running with MM methods in qcengine.
> Qcspec refactor

- codecov.yml
- qcsubmit/datasets.py
- qcsubmit/tests/test_datasets.py
- qcsubmit/tests/test_workflow_components.py
- qcsubmit/workflow_components/filters.py
Provide a brief description of the PR's purpose here.
This PR will speed up the deduplication steps in the workflow by using a dictionary indexed by the non-standard inchikey to store the molecules rather than a list. 
The API to iterate over the passed and filtered molecules is not changed however.
In preparation for the CLI a verbose flag has also been added to the initial deduplication stage which shows progress using tqdm.
Timing data:
On the 1156 molecules in the [AlkEthOH rings set](https://github.com/openforcefield/open-forcefield-data/blob/master/Model-Systems/AlkEthOH_distrib/AlkEthOH_rings.smi) deduplication now takes 1 second compared to ~4mins with the old method.
> Deduplication rework

- qcsubmit/datasets.py
- qcsubmit/tests/test_workflow_components.py
This PR will fix the tests by updating the coverage reporters to use the `ForceField.label_molecules` method in the new toolkit version=0.7.2.
> Toolkit update

- qcsubmit/datasets.py
- qcsubmit/exceptions.py
- qcsubmit/tests/test_datasets.py
- qcsubmit/validators.py
This PR will address #45 and adds warnings to constraints (both freeze and set) that are added between atoms that are not bonded.
Adds a `check_constraints` validator.
This will need to be worked into the validation reports in the QCA submissions repo as well.
> Nonbonded Constraint Validation

- qcsubmit/datasets.py
- qcsubmit/tests/test_datasets.py
This PR improves performance when dealing with datasets that contain a large number of molecules and/or conformers. Operations which include counting unique molecules or dataset searching lazy load TK molecules where possible and avoid building conformations always. 
This changes the API of the entry for building molecules from a property to a function `off_molecule` -> `get_off_molecule(include_conformers :bool)`. Conformers are still loaded when using the `dataset.molecules` generator.
> Improve large dataset performance

- qcsubmit/factories.py
- qcsubmit/tests/test_workflow_components.py
- qcsubmit/workflow_components/base_component.py
- qcsubmit/workflow_components/fragmentation.py
This PR makes use of QCElementals `which_import` function which allows us to raise detailed error messages with instructions on how to install missing packages for components.
New components which depend on a specific backend toolkit like openeye such as the protomer enumeration component can have import errors raised automatically by only setting openeye in the available toolkits dict and inheriting from the `ToolkitValidator` class
```python
class EnumerateProtomers(ToolkitValidator, CustomWorkflowComponent):
"""
Enumerate the formal charges of the input molecule using the backend toolkits through the OFFTK.
Note:
Only Openeye is supported so far.
"""
component_name = "EnumerateProtomers"
component_description = "Enumerate the protomers of the molecule if possible." …
```
> Improve missing package error messages.

- qcsubmit/datasets.py
- qcsubmit/tests/test_datasets.py
Missing basis coverage checks can often fail if the basis name can not be found in the basis set exchange package. Here we now convert basis with `*` or `/` in their name to the correct format allowing them to be validated correctly. 
`* -> _st_`
`/ -> _sl_`
> Improve missing basis checks

- qcsubmit/exceptions.py
- qcsubmit/factories.py
- qcsubmit/tests/test_workflow_components.py
- qcsubmit/workflow_components/__init__.py
- qcsubmit/workflow_components/base.py
- qcsubmit/workflow_components/base_component.py
- qcsubmit/workflow_components/conformer_generation.py
- qcsubmit/workflow_components/filters.py
- qcsubmit/workflow_components/fragmentation.py
- qcsubmit/workflow_components/state_enumeration.py
In order to make it easier for users to add new custom workflow components this switches to a factory design where they can registered. This allows qcsubmit to automatically load them from JSON/YAML if they have been registered first. We have also updated the pydantic models to use Fields to properly define the schema this will be expanded to factories and datasets latter.  
New components can now be registered using the new  function `register_component()`, they are then removed using `deregister_component()`. A list of all currently registered components can be generated using `list_components()` and finally an instance of a component can be made with its default settings using `get_component()`.
The fragmenter attribute `heuristic`  is removed to gain compatibility with fragmenter …
> Factory style workflow components

- qcsubmit/factories.py
- qcsubmit/validators.py
Expand the SCF property validator to allow for the new [MBIS properties](http://www.psicode.org/psi4manual/master/oeprop.html), this can be requested by adding the `mbis_charges` keyword to the `scf_properties` factory and dataset attributes. 
Fixes #63 
Also, remove an unused import.
> MBIS options

- devtools/conda-envs/psi4_env.yaml
- devtools/conda-envs/test_env.yaml
- qcsubmit/common_structures.py
- qcsubmit/data/invalid_linear_dataset.json
- qcsubmit/datasets/__init__.py
- qcsubmit/datasets/dataset_utils.py
- qcsubmit/datasets/datasets.py
- qcsubmit/datasets/entries.py
- qcsubmit/exceptions.py
- qcsubmit/tests/test_datasets.py
- qcsubmit/tests/test_results.py
- qcsubmit/tests/test_submissions.py
This PR changes how datasets are setup slightly to allow for more specific validation. We split out the dataset entry classes into 3 distinct types which have better validation. For example, only optimization datasets have entries with constraints and now torsiondrive entries must have a dihedral defined. Torsiondrive entries now have a defined set of keywords captured in the  `TDSettings` class rather than accepting a general dict to allow for validation of the unique scan settings which replace the general settings in the dataset.
Datasets should now be registered using the `register_dataset` function users can add there own as long as it is a subclass of `BasicDataset`.  Once registered the new util function `load_dataset` can instance the class from file or dict into the correct …
> Dataset update

- qcsubmit/datasets/datasets.py
- qcsubmit/tests/test_datasets.py
Here we improve the basis set coverage checking logic to handle cases such as the month or heavy basis sets. If we can not find the provided basis name we try some defined substitutions which attempt to strip the name down the core basis and validate based on this. There may still be some cases which cause errors but this [submission](https://github.com/openforcefield/qca-dataset-submission/pull/169) should now pass validation.
Fixes #69
> Basis set name logic

- devtools/conda-envs/psi4_env.yaml
- qcsubmit/common_structures.py
- qcsubmit/constraints.py
- qcsubmit/datasets/datasets.py
- qcsubmit/datasets/entries.py
- qcsubmit/factories.py
- qcsubmit/tests/test_datasets.py
- qcsubmit/tests/test_factories.py
- qcsubmit/tests/test_submissions.py
- qcsubmit/validators.py
This PR will change all schemas to use pydantic fields to fully define the model this should also help with the documentation.
> Pydantic Fields update

- qcsubmit/datasets/datasets.py
- qcsubmit/tests/test_submissions.py
- qcsubmit/utils.py
This PR should help with #68 by adding threading to submissions and is inspired by @trevorgokey spellbook. The optimization and torsiondrive datasets are chunked up and compute requests are made on subsets of the dataset of size 100. As this is not an option for normal datasets the threading is done across the specifications. It is intended that this will be built into the client eventually and will possibly be removed from here in future.
The await results flag has also been removed as this was not functional.
Until we have full logging support I have added some print statements with a verbose flag so users can see how many new tasks are created. 
> Threading submissions

- openff/qcsubmit/datasets/datasets.py
- openff/qcsubmit/tests/test_submissions.py
This is a temporary fix for #93. If no new entries are added to a dataset in qcarchive qcsubmit will now try and generate tasks for all entries present in the dataset,  tests added for optimization and torsiondrive datasets, normal dataset submission works slightly differently.
> Compute expansion fix

- openff/qcsubmit/common_structures.py
- openff/qcsubmit/factories.py
- openff/qcsubmit/tests/test_common_structures.py
This PR adds a convenience method to create a CMILES containing `MoleculeAttributes` object from an OpenFF molecule. This allows the object to be created directly without first needing to create a dataset factory first.
> Create CMILES object directly from a molecule

- openff/qcsubmit/tests/test_workflow_components.py
This PR fixes the current test failures by ensuring that multiple conformers are generated as part of the setup for the `test_rmsd_filter` unit test. This test likely started failing due to changes made by the RDKit 2021.03.1 release (#3813 in particular?) which coincides with when the CRON CI started to fail.
> Ensure multiple conformers generated for `test_rmsd_filter`

- openff/qcsubmit/results/filters.py
- openff/qcsubmit/results/results.py
- openff/qcsubmit/tests/results/conftest.py
- openff/qcsubmit/tests/results/test_filters.py
- openff/qcsubmit/tests/results/test_results.py
This PR exposes the initial API for filtering the results collections introduced in #106. It allows collections to be filtered directly:
```
filtered_collection = basic_result_collection.filter(
SMILESFilter(smiles_to_exclude=[...]),
SMARTSFilter(smarts_to_include=[...], 
)
```
where each filter is sequentially applied or alternatively individual filters can be applied:
```
filter = SMILESFilter(smiles_to_include=[...])
filtered_collection = filter.apply(basic_result_collection)
```
Provenance about the applied filters will be stored in a new result collection provenance field:
```
>>> filtered_collection.provenance["applied-filters"]
{
'SMILESFilter-0': {'smiles_to_exclude': [...]},
'SMARTSFilter-1': {'smarts_to_include': [...]},
}
```
> Add initial result filter API

- openff/qcsubmit/tests/results/__init__.py
- openff/qcsubmit/tests/results/conftest.py
This PR adds helper utilities to mock result collections and their associated QC records. This allows for rapid testing without calling out to QCA, and allows bespoke results to be generated depending on the requirements of each test.
> Add helpers to mock result collections

- openff/qcsubmit/results/results.py
This PR fixes the circular reference in the `results` module by ensuring that the `filter` module is only accessed by type hints.
> Remove circular reference in `results` module

- devtools/conda-envs/basic.yaml
- devtools/conda-envs/psi4.yaml
- openff/qcsubmit/results/caching.py
- openff/qcsubmit/results/filters.py
- openff/qcsubmit/results/results.py
- openff/qcsubmit/tests/conftest.py
- openff/qcsubmit/tests/results/conftest.py
- openff/qcsubmit/tests/results/test_caching.py
- openff/qcsubmit/tests/results/test_filters.py
- openff/qcsubmit/tests/results/test_results.py
This PR adds a number of helper methods which enable caching queries to a `QCFractal` instance, as well as retrieving the records associated with a result collection.
These changes will likely be superseded by https://github.com/MolSSI/QCFractal/pull/671 (or its successors) when ready.
> Add cached versions of QC record and molecule queries

- openff/qcsubmit/results/filters.py
- openff/qcsubmit/tests/results/test_filters.py
This PR adds a new `ResultRecordFilter` base class for new filters which will filter based information contained in records themselves, rather than just based on a record id or CMILES / InChI. The filter handles all of the batched record retrievals and only requires sub-filters to define a method to either retain or reject a result based on it's corresponding record.
> Add base class for result record filters

- openff/qcsubmit/results/filters.py
- openff/qcsubmit/tests/results/test_filters.py
This PR adds two new filters:
* `HydrogenBondFilter` - filters out hydrogen bond containing records
* `ConnectivityFilter` - filters out records where the final and initial molecules have different connectivities
> Add h-bond and connectivity results filters

- openff/qcsubmit/common_structures.py
This PR make `openmmforcefields` an optional dependency. This removes the second-hand `ambertools` dependency of this package and makes it easier to install alongside `psi4` when GAFF isn't needed.
> Make `openmmforcefields` an optional dependency

- openff/qcsubmit/results/filters.py
- openff/qcsubmit/tests/results/test_filters.py
This PR adds a new `CMILESResultFilter` common base class from which filters which will retain selection of QC records based solely on the CMILES ( / InChI key) associated with the record itself (e.g. SMILES and SMARTS based filters) should inherit from.
> Add base class for CMILES results filters

- openff/qcsubmit/results/filters.py
- openff/qcsubmit/tests/results/test_filters.py
This PR adds a `RecordStatusFilter` filter which will only retain records whose status matches a specified value.
> Add record status result filter

- openff/qcsubmit/common_structures.py
- openff/qcsubmit/datasets/datasets.py
This PR ensures that `qcfractal` is an optional import and hence can be made an optional dependency. In most cases it seems like only `qcportal` should be required which is a much lighter package.
> Make `qcfractal` an optional import

- openff/qcsubmit/common_structures.py
- openff/qcsubmit/data/invalid_double_torsion_dataset.json
- openff/qcsubmit/data/invalid_improper_dataset.json
- openff/qcsubmit/data/invalid_linear_dataset.json
- openff/qcsubmit/data/invalid_torsion_dataset.json
- openff/qcsubmit/data/valid_double_torsion_dataset.json
- openff/qcsubmit/data/valid_improper_dataset.json
- openff/qcsubmit/data/valid_torsion_dataset.json
- openff/qcsubmit/datasets/entries.py
- openff/qcsubmit/tests/test_common_structures.py
- openff/qcsubmit/tests/test_factories.py
We often use fixed hydrogen inchi key for fast deduplication, this PR adds the fixed hydrogen inchi and inchikey to the `MoleculeAttributes` object, these fields are automatically generated still via the `from_openff_molecule` classmethod. A convenient method to generate an openff molecule from the MoleculeAttributes is also added called `to_openff_molecule`.
> Add fixed hydrogen inchi/inchikey to attributes

- openff/qcsubmit/results/filters.py
- openff/qcsubmit/results/results.py
This PR fixes issues when creating molecules from SMILES patterns whose stereochemistry is not fully defined in the CMILES (e.g. cases where OE thinks a N is a stereocenter but RDKit does not).
> Fix stereochemistry error when creating molecule from SMILES

- openff/qcsubmit/results/results.py
This PR fixes a key error raised when creating a result collection from a data set. This occurs when the dataset contains an entry not present in the query for a given spec name.
> Fix key error when entry not in result query

- openff/qcsubmit/tests/test_workflow_components.py
- openff/qcsubmit/workflow_components/filters.py
This PR implements a minimum rotatable bond option for the RotorFilter to finish PR #74.
> Rotor update

- openff/qcsubmit/results/caching.py
- openff/qcsubmit/results/results.py
- openff/qcsubmit/tests/results/__init__.py
- openff/qcsubmit/tests/results/test_caching.py
- openff/qcsubmit/tests/results/test_results.py
This PR adds a convenience method to create a basic data set collection from an existing optimization result collection. This would allow, for example, being able to find all of the hessian result records which were generated using the final structure of a set of optimizations.
This may be preferable in certain cases to just creating the basic result collection itself. This is especially true when trying to create a result collection from an older dataset which does not have CMILES information attached. This method will propagate the parent optimization CMILES down to the child basic result record thus circumventing this issue.
> Add optimization result collection to basic result collection

- openff/qcsubmit/common_structures.py
In order to help with loading older datasets, this PR makes the new non-standard attributes optional.
> Make non-standard attributes optional

- openff/qcsubmit/datasets/datasets.py
- openff/qcsubmit/tests/test_datasets.py
This PR fixes a deduplication issue when trying to store extra conformers for a molecule that was originally saved with none. Now molecules are stored with an empty list of conformers if they have none when first stored.
> Component result update

- openff/qcsubmit/datasets/datasets.py
- openff/qcsubmit/tests/test_factories.py
This PR fixes #131 by removing atom maps from molecules once they enter into the workflow. We do this as we can not guarantee that they will survive the various workflow components and can cause unexpected behaviour if they are present when not expected.
> Remove atom maps

- openff/qcsubmit/results/filters.py
- openff/qcsubmit/tests/results/__init__.py
- openff/qcsubmit/tests/results/conftest.py
- openff/qcsubmit/tests/results/test_filters.py
This PR adds the `LowestEnergyFilter` which can be used on Basic and Optimisation results collections to reduce down the number of repeated entries for a molecule to a single entry corresponding to the lowest energy structure. 
> LowestEnergyFilter

- openff/qcsubmit/results/filters.py
- openff/qcsubmit/tests/results/test_filters.py
This PR adds a new filter which aims to retain up to a maximum number of maximally distinct conformers for each molecule in an optimization or a basic result collection while conformers similar to within an RMSD threshold are discarded.
> Add conformer RMSD result filter

- docs/conf.py
- docs/environment.yml
This PR fixes the API documentation rendering by ensuring the OpenFF toolkit can be imported.
> Fix mocking imports for sphinx doc builds

- openff/qcsubmit/common_structures.py
- openff/qcsubmit/tests/test_common_structures.py
- openff/qcsubmit/tests/test_datasets.py
- openff/qcsubmit/tests/test_submissions.py
This PR makes the `Metadata.long_description_url` optional as it is likely unneeded for private and local submissions.
> Make `long_description_url` metadata optional

- openff/qcsubmit/common_structures.py
- openff/qcsubmit/datasets/datasets.py
- openff/qcsubmit/tests/test_datasets.py
This PR adds the ability to add optional `keywords` to datasets via the associated `QCSpec` specifications.
> Expose keywords via the QCSpec

- openff/qcsubmit/results/caching.py
- openff/qcsubmit/tests/results/test_caching.py
This PR fixes a bug where data could not be retrieved from a local QCFractal snowflake due to the client verification failing and hence the connection being refused.
> Fix retrieving data from snowflake server

- openff/qcsubmit/results/caching.py
This PR sorts the torsiondrive final configurations stored in the molecule returned from the `to_records` function in the results class so that they logically follow the scan order.
> Order torsiondrive results

- openff/qcsubmit/factories.py
- openff/qcsubmit/tests/test_workflow_components.py
- openff/qcsubmit/workflow_components/__init__.py
- openff/qcsubmit/workflow_components/base_component.py
- openff/qcsubmit/workflow_components/conformer_generation.py
- openff/qcsubmit/workflow_components/filters.py
- openff/qcsubmit/workflow_components/fragmentation.py
- openff/qcsubmit/workflow_components/state_enumeration.py
This PR allows the workflow components and the dataset factories to take a toolkit registry object that declares the available backend toolkits and their querying presence for functionality. If `None` is passed the default global toolkit registry will be used which contains all currently installed toolkits. This replaces the per-component toolkit argument. The provenance information now contains all toolkits in the passed toolkit registry.
> Toolkit registry

- openff/qcsubmit/datasets/datasets.py
- openff/qcsubmit/datasets/entries.py
- openff/qcsubmit/results/caching.py
- openff/qcsubmit/results/filters.py
- openff/qcsubmit/tests/results/__init__.py
- openff/qcsubmit/tests/results/conftest.py
- openff/qcsubmit/tests/results/test_caching.py
- openff/qcsubmit/tests/results/test_filters.py
- openff/qcsubmit/tests/results/test_results.py
- openff/qcsubmit/tests/test_datasets.py
- openff/qcsubmit/tests/test_workflow_components.py
- openff/qcsubmit/validators.py
- openff/qcsubmit/workflow_components/filters.py
- openff/qcsubmit/workflow_components/utils.py
I noticed tests were failing due to the API breaks in OpenMM 7.6. I tried to update everything to work with the new version (avoiding deprecation warnings) but also be compatible with 7.5.x. I was unable to test everything locally but the major one in `ElementFilter` should be fixed.
> Update OpenMM imports for 7.6 and backwards compatibility

- devtools/conda-envs/basic.yaml
- devtools/conda-envs/psi4.yaml
- docs/api.rst
- openff/qcsubmit/results/filters.py
- openff/qcsubmit/tests/results/test_filters.py
This PR adds a new filter that only retains records for associated with a particular unique molecule if that molecule has a certain number of records (i.e. conformers) associated with it.
This is useful, for example, when you want to train to relative energies and hence need to make sure there are at least 2 conformers present. This is especially true when used in conjunction with the `ConformerRMSDFilter`.
> Add minimum N conformers result filter

- openff/qcsubmit/results/results.py
This PR aims to patch errors raised when mapping an optimizations collection to a basic collection caused by issues in the QCFractal server.
From slack:
I'm trying to pull some result records (gradient and hessian) from QCA but I'm getting a connection refused error:
```
from qcportal import FractalClient
client = FractalClient('https://api.qcarchive.molssi.org:443/')
results = client.query_results(
program='psi4',
molecule=[
'12160621', '12162704', '12159790', '12168415',
'12164932', '12154972', '12158785', '12176447',
'12182844', '12170904', '12183903'
],
driver=['gradient', 'hessian'],
method='b3lyp-d3bj',
basis='dzvp',
status='COMPLETE'
)
```
> ../../../../../miniconda3/envs/descent/lib/python3.9/site-packages/qcportal/client.py:718: in query_results
>     response = …
> Filter by keywords when mapping to basic collection

- openff/qcsubmit/results/filters.py
- openff/qcsubmit/results/results.py
- openff/qcsubmit/tests/results/__init__.py
- openff/qcsubmit/tests/results/conftest.py
- openff/qcsubmit/tests/results/test_filters.py
This PR updates the results classes and filters to use the fixed hydrogen map inchi key to ensure tautomers are correctly distinguished.
> Switch results to fix hydrogen inchikey

- openff/qcsubmit/datasets/datasets.py
- openff/qcsubmit/tests/test_datasets.py
This PR adds support for a psi4 spec with a basis of None assuming it has been combined with the method. A warning is now printed to inform that the element coverage can not be validated.
> Support for psi4 None basis

- .github/workflows/CI.yml
- devtools/conda-envs/basic.yaml
- devtools/conda-envs/psi4.yaml
Try and pin qcelemental to fix the psi4 local compute tests.
The psi4 CI testing seems to have broken around the time of the new `qcelemental=0.23.0` release. The error is due to a numpy array not being converted to a list before trying to form the JSON when saving results in a qcfractal db. Unfortunately the error is truncated in the CI report so we can't see which property is causing the issue. 
```
File "/usr/share/miniconda/envs/test/lib/python3.7/json/encoder.py", line 179, in default
raise TypeError(f'Object of type {o.__class__.__name__} '
sqlalchemy.exc.StatementError: (builtins.TypeError) Object of type ndarray is not JSON serializable
[SQL: INSERT INTO result (id, program, driver, method, basis, molecule, keywords, return_result, properties, wavefunction, wavefunction_data_id) …
```
> Testing fixes

- devtools/conda-envs/basic.yaml
- devtools/conda-envs/psi4.yaml
- openff/qcsubmit/common_structures.py
- openff/qcsubmit/datasets/datasets.py
Along with MolSSI/QCFractal#693, addresses #167.
> Use of `additional_keywords` for per-torsiondrive-entry constraints

- openff/qcsubmit/factories.py
- openff/qcsubmit/tests/test_datasets.py
- openff/qcsubmit/tests/test_factories.py
This PR makes the dataset factories raise a `FileNotFound` error when the input file can not be found. This is an improvement over the current unbound local error.
> Clear Error for missing inputs

- openff/qcsubmit/datasets/datasets.py
- openff/qcsubmit/datasets/entries.py
- openff/qcsubmit/tests/test_datasets.py
Currently, [we observe failures](https://github.com/openforcefield/qca-dataset-submission/runs/4459934379?check_suite_focus=true#step:8:24) when calling `Dataset.add_molecule` when feeding in `molecule=None`, whereas this was permitted previously.
This appears due to the use of `kwargs.pop`, with `MoleculeAttributes.from_openff_molecule(molecule=molecule)` as the default value. This gets called even if 'attributes' is present as a key in the dictionary. This PR separates these operations to avoid this call.
> Only call `Molecule.from_openff_molecule` if 'attributes' not present in `Dataset.add_molecule` kwargs

- openff/qcsubmit/results/results.py
This PR has a workaround for loading datasets with the fixed hydrgoen inchi key set to `None` such as the `OpenFF-benchmark-ligand-fragments-v2.0` dataset which contains a mix of new and old calculations. 
Types are also added to the collections so that they can be distinguished before loading into a model.
> Result collections with None inchikeys

- openff/qcsubmit/common_structures.py
- openff/qcsubmit/results/results.py
- openff/qcsubmit/tests/results/test_results.py
This PR is a simple fix for creating basic dataset results from collections with NaNs, representing records to be computed. See [here](https://github.com/MolSSI/QCFractal/issues/706) for a better fix that won't involve qcsubmit doing a second filter.
> Fix dataset record queries with nans

- openff/qcsubmit/common_structures.py
- openff/qcsubmit/datasets/datasets.py
This removes chunked calls to `dataset.save` as entries (molecules) are added to a given dataset as part of submission, as these are unnecessary and only serve to slow submission as the collection object grows with additional entries added.
We also added in a performance hack for single point `Dataset`s only, in which we only call `collection.save` on the first call for a given spec addition and then again after all tasks are generated. This saves repeated movement of the collection object, which is unchanged as tasks are generated over the course of the loop.
Requires a new release of QCFractal beyond the current 0.15.7 release, in particular MolSSI/QCFractal#705.
> Removed chunked saves for entry submission; added performance hack for single point task submission

- openff/qcsubmit/common_structures.py
- openff/qcsubmit/results/results.py
- openff/qcsubmit/tests/results/test_results.py
This PR fixes a bug where an `OptimizationResultCollection` will drop multiple conformers for molecules when creating a basic dataset from the result.
> keep multiple conformers when creating a basic dataset from an `OptimizationResultCollection`

- openff/qcsubmit/results/caching.py
This PR addresses #201 by supporting TorsionDrives with multi-dimensional grid indices.
> Support multi-dimensional TorsionDrive grid indices

- devtools/conda-envs/docs.yaml
- openff/qcsubmit/common_structures.py
- openff/qcsubmit/tests/test_datasets.py
The current logic makes it difficult to use QC packages supported by QCEngine besides Psi4. This updates the logic to _not_ assume that the `program` argument is in the `settings` dictionary.
> Improve compatibility with non-Psi4 engines

- .github/workflows/CI.yml
- devtools/conda-envs/basic.yaml
- devtools/conda-envs/docs.yaml
- devtools/conda-envs/psi4.yaml
- docs/conf.py
- openff/qcsubmit/datasets/entries.py
- openff/qcsubmit/results/caching.py
- openff/qcsubmit/results/filters.py
- openff/qcsubmit/tests/results/__init__.py
- openff/qcsubmit/tests/results/conftest.py
- openff/qcsubmit/tests/results/test_caching.py
- openff/qcsubmit/tests/results/test_filters.py
- openff/qcsubmit/tests/results/test_results.py
- openff/qcsubmit/tests/test_datasets.py
- openff/qcsubmit/tests/test_workflow_components.py
- openff/qcsubmit/utils/smirnoff.py
- openff/qcsubmit/workflow_components/filters.py
- openff/qcsubmit/workflow_components/utils.py
Update QCSubmit to work with the OpenFF Toolkit 0.11+
Supersedes #203 
Test failures (running locally on my machine):
> Toolkit 0.11 support

- devtools/conda-envs/basic.yaml
- openff/qcsubmit/utils/utils.py
Resolves #209
The function `get_torsion` included in its logic some empheral `Atom` objects with atomic numbers of 0, which are now forbidden. I've changed the logic to avoid needing to do this. The behavior is the same as far as I understand the function to work.
I've also taken the liberty of updating some outdated bits in the test environment.
> Update `get_torsion` for OpenFF Toolkit 0.12

- openff/qcsubmit/results/results.py
- openff/qcsubmit/tests/results/conftest.py
- openff/qcsubmit/tests/results/test_results.py
> Make loading datasets skip over corrupt entries with invalid CMILES

- devtools/conda-envs/basic.yaml
- devtools/conda-envs/psi4.yaml
- openff/qcsubmit/tests/test_workflow_components.py
- openff/qcsubmit/validators.py
[openff-toolkit 0.14.1](https://docs.openforcefield.org/projects/toolkit/en/stable/releasehistory.html#api-breaking-changes) removed the deprecated ChemicalEnvironment class and its associated module. We only used this in one place (plus a re-export of an exception type). This PR cleans up that one call site as suggested by @j-wags.
> Update QCSubmit for removal of ChemicalEnvironment class in OFFTK >0.14.1

- openff/qcsubmit/datasets/datasets.py
- openff/qcsubmit/tests/test_datasets.py
- openff/qcsubmit/tests/test_submissions.py
[`OptimizationProtocols`](https://github.com/MolSSI/QCElemental/blob/1ef6b52adc4a18cfd6a2cfc1b56880daaeea3a44/qcelemental/models/procedures.py#L32-L48) allow users to e.g. only save gradients, wavefunctions for starting and final geometries of an optimization, reducing storage requirements for results. The changes here expose this functionality through QCSubmit, allowing users to set `OptimizationProtocols` settings other than the defaults if desired.
> Expose ability to set OptimizationProtocols for for optimizations, torsiondrives

- docs/releasehistory.md
- openff/qcsubmit/_tests/test_datasets.py
- openff/qcsubmit/workflow_components/utils.py
Taking @lilyminium's suggestion in #255 and just seeing what happens in tests.
Not squatting on this at all; if somebody wants to move this forward please feel free to use this branch/PR.
> Add `aromatic_matching=False` to isometry check

- docs/installation.md
Our install docs were referring people to `devtools/conda-envs/meta.yaml`, which doesn't exist any more. We could either point them to `psi4.yaml` or `basic.yaml`. I think basic is better since it's more likely to be devs installing from source, and they'll know how to install psi4 afterwards if they need.
> Fix install instructions

- devtools/conda-envs/basic.yaml
- devtools/conda-envs/psi4.yaml
#275 is causing false negatives, so I'd like to pin this the upstream versions that are known to be compatible
> Pin QCPortal to 0.53

- devtools/conda-envs/basic.yaml
- devtools/conda-envs/psi4.yaml
- docs/releasehistory.md
- examples/retrieving-results.ipynb
This PR adds the 2D torsion drive visualization from the 2024 SMIRNOFF workshop (gist [here](https://gist.github.com/j-wags/57cd258af4465610205da9e486791140#file-env-yaml)) to the existing `retrieving-results.ipynb` example. This was a pretty small change but also required adding `plotly` and `nglview` as dependencies in the CI environments and updating a little bit of the prose in the example.
> Merge fetch_qc_torsiondrive example into retrieving-results

- docs/releasehistory.md
- openff/qcsubmit/_tests/test_workflow_components.py
- openff/qcsubmit/workflow_components/__init__.py
- openff/qcsubmit/workflow_components/base.py
- openff/qcsubmit/workflow_components/fragmentation.py
This PR adds a new workflow component to perform fragmentation using the RECAP method implemented in RDkit. This has been used in the past [ESP datasets](https://github.com/openforcefield/qca-dataset-submission/blob/master/submissions/2022-01-16-OpenFF-ESP-Fragment-Conformers-v1.0/README.md) and will be used in newly generated ones so having formal support should make dataset curations scripts simpler and reproducible. 
> Add RECAP fragmentation

- docs/api.rst
- openff/qcsubmit/_tests/results/test_filters.py
- openff/qcsubmit/_tests/results/test_results.py
- openff/qcsubmit/_tests/test_submissions.py
- openff/qcsubmit/results/results.py
- openff/qcsubmit/utils/__init__.py
- openff/qcsubmit/utils/utils.py
This PR uses the [get_records_with_cache](https://github.com/MolSSI/QCFractal/blob/5e35393e150fb67a528f26549b6f9ea3bc68c186/qcportal/qcportal/cache.py#L590) function discussed in our last QCArchive meeting to cache `to_records` calls automatically. With these changes alone, users cannot actually access this behavior, but when combined with #284, it enables code like this:
```python
from qcportal import PortalClient
from openff.qcsubmit._tests.utils.test_manager import no_internet
from openff.qcsubmit.results import OptimizationResultCollection
from openff.qcsubmit.utils.utils import portal_client_manager
opt = OptimizationResultCollection.parse_file("tiny-opt-dataset.json")
client = PortalClient("https://api.qcarchive.molssi.org:443", cache_dir=".")
with portal_client_manager(lambda _: …
```
> Use `get_records_with_cache` to cache `to_records` calls

- .github/workflows/CI.yml
Based on the CI errors, I think we're just missing the token. I also changed `fail_ci_if_error` to `true` in-line with the toolkit repo.
Enable codecov coverage checks in CI. There was already a step in CI.yml for this, but no token was being provided and `fail_ci_if_error` was `false`, so it was silently failing each time.
> Re-enable codecov

- devtools/conda-envs/basic.yaml
- devtools/conda-envs/psi4.yaml
Old versions of `apsw` (i.e. 3.39.2.1  from earlier today) are pulled down by testing environments but [QCFractal needs newer versions](https://github.com/conda-forge/qcfractal-feedstock/pull/52/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aL51) like 3.42+. This patch fixes the test environment.
> Fix tests by pulling down more recent `apsw`

- docs/releasehistory.md
- openff/qcsubmit/_tests/results/__init__.py
- openff/qcsubmit/_tests/results/test_results.py
- openff/qcsubmit/results/results.py
The goal of this PR is a long-term fix to #297. In short, the current `OptimizationResultCollection.create_basic_dataset` implementation creates a new dataset by round-tripping through OpenFF `Molecule`s, which causes issues with the hashing/equivalence checks in QCArchive, leading to "the same molecules" being considered different. In turn, this causes `OptimizationResultCollection.to_basic_result_collection` to return fewer records than expected.
Earlier qca-dataset-submissions ([example](https://github.com/openforcefield/qca-dataset-submission/blob/95809b4d5a98a118e340b393fdd3636ad24a8606/submissions/2019-07-05%20OpenFF%20NCI250K%20Boron%201/04_create_hessian_dataset.py#L4)) manually constructed qcportal datasets instead of using qcsubmit datasets to avoid this round trip. Due to the …
> Update `OptimizationResultCollection.create_basic_dataset` to preserve molecule IDs

- devtools/conda-envs/basic.yaml
We don't need this:
```
$ micromamba create --file devtools/conda-envs/basic.yaml
conda-forge/noarch                                          Using cache
conda-forge/osx-arm64                                       Using cache
warning  libmamba 'repo.anaconda.com', a commercial channel hosted by Anaconda.com, is used.
warning  libmamba Please make sure you understand Anaconda Terms of Services.
warning  libmamba See: https://legal.anaconda.com/policies/en/
warning  libmamba 'repo.anaconda.com', a commercial channel hosted by Anaconda.com, is used.
warning  libmamba Please make sure you understand Anaconda Terms of Services.
warning  libmamba See: https://legal.anaconda.com/policies/en/
warning  libmamba 'repo.anaconda.com', a commercial channel hosted by Anaconda.com, is used.
warning …
```
> Drop use of `defaults` conda channel

- .github/workflows/CI.yml
- devtools/conda-envs/basic.yaml
- devtools/conda-envs/psi4.yaml
> Bump upstream(s) used in tests

- openff/qcsubmit/exceptions.py
- openff/qcsubmit/results/results.py
Fixes https://github.com/openforcefield/openff-bespokefit/issues/393 by raising a more useful error message.
Arguably this could be a warning instead of an error, but there is potential for a significant behavior change if i.e. a fit is run on a partially-complete torsion drive dataset and re-run later when the compute is complete. This is not necessarily wholly bad, but an opinionated change we did not want to make here.
(Some extra comments in the code, and much more context in the linked issue.)
> Error when torsion drive is probably still running
