qcsubmit/datasets.py, qcsubmit/factories.py, qcsubmit/tests/test_datasets.py, qcsubmit/tests/test_submissions.py, qcsubmit/tests/test_workflow_components.py, qcsubmit/utils.py, qcsubmit/validators.py, qcsubmit/workflow_components/base_component.py
Add columns args to visualize method.
=> update visualize to take columns args.

devtools/conda-envs/psi4_env.yaml, devtools/conda-envs/test_env.yaml, qcsubmit/results.py, qcsubmit/tests/test_results.py
This provides a fix to the function which orders the torsiondrive optimizations by the angle.
Also adds extras tests for the results classes.
=> Fix torsiondrive order error

devtools/scripts/create_conda_env.py, qcsubmit/common_structures.py, qcsubmit/constraints.py, qcsubmit/datasets.py, qcsubmit/exceptions.py, qcsubmit/results.py, qcsubmit/tests/test_datasets.py, qcsubmit/tests/test_results.py, qcsubmit/utils.py, qcsubmit/validators.py, setup.py, versioneer.py
Add a validated dataset entry attribute for constraints. Also make sure sure that results to dataset converters transfer all constraints.
This will add support for `freeze` and `set` type constraints, the constraint format is validated.
=> Constraint validation

qcsubmit/datasets.py, qcsubmit/factories.py, qcsubmit/tests/test_datasets.py
This PR fixes a bug where the torsiondrive validators caused molecules with multiple torsions selected for driving to be set to all be the same.
=> Fix torsiondrive duplication bug

qcsubmit/tests/test_workflow_components.py, qcsubmit/workflow_components/filters.py
This PR adds the ability to tag dihedrals for torsiondrive via the smarts filter similar to the coverage filter.
=> Tag dihedrals via Smarts filter

qcsubmit/datasets.py, qcsubmit/tests/test_submissions.py
Fixes #62 
Here we update the way specifications are added to datasets to handle a few cases. 
- If we try to add a specification with the same name as another and the settings are the same we reuse the specification
- If we try to add a specification with the same name as another but the settings are different:
- if the specification has been used for computing we throw an error telling the user to change the name of this new spec as the old one should not be overwritten.
- if the specification has not been used then we can overwrite it and add our new one.
I have also added tests for each of these cases. This only effects Optimization and TorsionDrive Datasets.
=> Update specification adding

qcsubmit/datasets/datasets.py, qcsubmit/tests/test_datasets.py
This PR fixes #60 by changing the isomorphic check to be more relaxed and match the inchikey comparison, I also add a test using the example molecules from the tagged issue.
=> Workflow deduplication fix

qcsubmit/procedures.py
This will fix #83 and update the geometric procedure to use fields to fully describe the schema which should help with documentation in the future. Note this removes some overly complicated validator functions in favour for the Literal type hint.
=> Geometric schema fix

qcsubmit/datasets/datasets.py, qcsubmit/tests/test_submissions.py
This fixes #78 by stoping any index expansion when only supplying one conformer for a dataset/optimizationdataset entry.
=> Single index fix

README.md
Update the badges to match the namespace and repo name change.
=> update the badges

openff/qcsubmit/procedures.py, openff/qcsubmit/tests/test_results.py, openff/qcsubmit/validators.py, setup.py
This adds two general literal case validators which should help avoid case sensitive validation failures for literal types.
=> Geometric update

devtools/conda-envs/psi4_env.yaml, devtools/conda-envs/test_env.yaml, openff/qcsubmit/common_structures.py, openff/qcsubmit/tests/test_submissions.py, setup.py
Fixes #79 by lowering the list of installed forcefields from the openforcefield toolkit. Also added a test to run one of these in production.
=> Fix Smirnoff99Frosst validation

openff/qcsubmit/results/filters.py, openff/qcsubmit/tests/results/test_filters.py
This PR adds two new filters which filter a results collection be a set of SMARTS and SMILES patterns respectively.
=> Add SMARTS and SMILES result filters

openff/qcsubmit/results/results.py, openff/qcsubmit/tests/results/__init__.py, openff/qcsubmit/tests/results/test_results.py
This PR updates the return value of the result collection `to_records` function to also include a corresponding molecule object which stores relevant conformers.
For basic results collections the molecule contains just the conformer of the original molecule, for optimizations it contains the conformer of the final molecule, and for torsion drives it contains the final conformer of each grid angle (i.e. `n_conformers == n_grid_points`) in addition to a `grid_ids` entry in the properties dictionary which also stores which grid angle / id each conformer corresponds to.
The functionality is built of the cached helper methods introduced in #113.
=> Include corresponding final molecule in `to_records`

openff/qcsubmit/results/filters.py, openff/qcsubmit/tests/results/test_filters.py, openff/qcsubmit/validators.py
This PR adds a charge result filter.
=> Charge result filter

openff/qcsubmit/results/filters.py, openff/qcsubmit/tests/results/test_filters.py, openff/qcsubmit/tests/test_workflow_components.py, openff/qcsubmit/validators.py, openff/qcsubmit/workflow_components/filters.py
This PR adds a results element filter.
=> Results Element filter

openff/qcsubmit/results/filters.py, openff/qcsubmit/tests/results/test_filters.py
This PR adds a filter that drops records for which stereochemistry information cannot be perceived by the OpenFF toolkit from the 3D conformers associated with that record.
This filter is mainly useful for catching edge cases whereby the stereochemistry perceived by an underlying cheminformatics toolkit does not match what the OpenFF toolkit expects (mainly occurs with planar amine nitrogens IIRC).
=> Add result filter for unperceivable 3D stereochemistry

docs/api.rst
Add the `ChargeFilter` to the docs.
=> add ChargeFilter to the docs

openff/qcsubmit/serializers.py, openff/qcsubmit/tests/test_serializers.py
This PR fixes #176 by correctly raising a `FileNotFoundError`. Type hints are also added for the available compression types.
=> Deserializer Error Fix

.github/workflows/CI.yml, .github/workflows/Lint.yaml, README.md
Various updates corresponding to the master branch being renamed main.
=> update `master` -> `main`

devtools/conda-envs/basic.yaml, devtools/conda-envs/psi4.yaml
=> Testing fix

.github/workflows/CI.yml, devtools/conda-envs/basic.yaml, devtools/conda-envs/docs.yaml, devtools/conda-envs/psi4.yaml
Miniconda is slow, micromamba is a bit less slow.
=> Use micromamba in CI

docs/releasehistory.md
I tend to forget to make these during development
=> Add 0.3.2 release notes

docs/releasehistory.md
Provide a brief description of the PR's purpose here.
=> Add 0.4.0 release notes

docs/conf.py, docs/installation.md
Adds a link to the ecosystem install guide to the project install guide
=> Add link to ecosystem docs

.github/workflows/Lint.yaml, openff/qcsubmit/common_structures.py, openff/qcsubmit/datasets/datasets.py, openff/qcsubmit/datasets/entries.py, openff/qcsubmit/exceptions.py, openff/qcsubmit/factories.py, openff/qcsubmit/results/caching.py, openff/qcsubmit/results/filters.py, openff/qcsubmit/results/results.py, openff/qcsubmit/utils/smirnoff.py, openff/qcsubmit/utils/visualize.py, openff/qcsubmit/workflow_components/base_component.py, openff/qcsubmit/workflow_components/filters.py, openff/qcsubmit/workflow_components/fragmentation.py, openff/qcsubmit/workflow_components/state_enumeration.py, openff/qcsubmit/workflow_components/utils.py
The context here is identical to https://github.com/openforcefield/openff-bespokefit/pull/225
* `black` introduced its annual breaking changes late January, which causes the linting action to fail
* The action just installs the latest version; other tools like `pre-commit` allow for more control over updates
* Other PRs now fail the linting checks
* I don't like their style changes, Josh Horton seems to agree with me, but (my opinion) it's what one gives up using opinionated tools
=> Update for Black 23

.github/workflows/CI.yml, README.md, devtools/conda-envs/basic.yaml, devtools/conda-envs/docs.yaml, devtools/conda-envs/psi4.yaml, openff/qcsubmit/tests/results/test_caching.py, openff/qcsubmit/tests/test_submissions.py
=> Testing fix and update for Psi4 >1.5

devtools/conda-envs/basic.yaml, devtools/conda-envs/psi4.yaml
Provide a brief description of the PR's purpose here.
=> Pin to legacy QCFractal in CI

docs/releasehistory.md, openff/qcsubmit/results/results.py
This PR is a small patch to fix #236. The MWE there runs correctly with this patch.
=> OpenMM to OpenFF units in results/results.py

.github/workflows/CI.yml
I noticed this repo hasn't been updated yet.
=> Switch to new `micromamba` action

.pre-commit-config.yaml, examples/creating-datasets.ipynb, examples/retrieving-results.ipynb, openff/qcsubmit/__init__.py, openff/qcsubmit/_pydantic.py, openff/qcsubmit/_tests/results/test_filters.py, openff/qcsubmit/_tests/test_serializers.py, openff/qcsubmit/_tests/test_workflow_components.py, openff/qcsubmit/common_structures.py, openff/qcsubmit/constraints.py, openff/qcsubmit/datasets/dataset_utils.py, openff/qcsubmit/datasets/entries.py, openff/qcsubmit/results/results.py, openff/qcsubmit/testing.py, openff/qcsubmit/validators.py, openff/qcsubmit/workflow_components/filters.py, openff/qcsubmit/workflow_components/fragmentation.py, openff/qcsubmit/workflow_components/state_enumeration.py, openff/qcsubmit/workflow_components/utils.py
Would be worth coordinating #258
=> Consistently lint notebooks

docs/releasehistory.md, examples/creating-datasets.ipynb, openff/qcsubmit/utils/visualize.py
Fixes #200; I verified the bug and fix locally
=> Fix dataset visualization with RDKit backend

devtools/conda-envs/psi4.yaml
=> up-constrain psi4 to >=1.9.1

.pre-commit-config.yaml, openff/qcsubmit/common_structures.py
Context https://github.com/openforcefield/openff-qcsubmit/pull/277#issuecomment-2073339133
=> Fix linting quirk

devtools/conda-envs/basic.yaml, devtools/conda-envs/psi4.yaml, openff/qcsubmit/_pydantic.py, openff/qcsubmit/common_structures.py
https://docs.pydantic.dev/latest/changelog/#v11018-2024-08-22), 
=> Use new Pydantic v1 backdoor

devtools/conda-envs/basic.yaml, devtools/conda-envs/psi4.yaml
=> Use Plotly 5 in examples

devtools/conda-envs/basic.yaml, devtools/conda-envs/psi4.yaml
Resolves #331 - should bring down 0.4.2
=> Use `openmmforcefields` 0.14.2
